#!/usr/bin/env python3

import os

conf = os.environ.get("conf")
configfile: conf
execDir = config['execDir']
outDir = config['part2']['outDir']
inDir = config['part3']['inDir']
numSigs = str(config['part3']['numSigs'])
GROUPS = config['part2']['groups']
GROUPS.append('total')

rule all:
    input:
        expand(outDir + 'SomaticSigs_out/{group}_' + numSigs + '_sigs.txt', group=GROUPS),
        expand(outDir + 'SomaticSigs_out/{group}_' + numSigs + '_sigs.png', group=GROUPS),
        expand(outDir + 'SomaticSigs_out/{group}_' + numSigs + '_sigs_by_sample.png', group=GROUPS)

rule find_signatures:
    input:
        inDir + '{group}_mm_summed'
    output:
        outDir + 'SomaticSigs_out/{group}_' + numSigs + '_sigs.txt',
        outDir + 'SomaticSigs_out/{group}_' + numSigs + '_sigs.png',
        outDir + 'SomaticSigs_out/{group}_' + numSigs + '_sigs_by_sample.png'
    params:
        path = execDir + 'scripts/',
        n = numSigs,
        outBase = outDir + 'SomaticSigs_out/{group}_' + numSigs
    shell:
        'module load gcc/4.8.4 R/3.4.0;'
        'Rscript {params.path}runSomaticSigs.r {params.n} {wildcards.group} {input} {params.outBase}'
