#!/usr/bin/env python3

# detect dinucleotide mutations

# Dinucleotide substitutions were identified when two substitutions were present in consecutive bases on the same chromosome (sequence context was ignored). 

    # assuming a sorted SNV-only vcf:
        # for each column, if adjacent rows have a non-wt and non-missing genotype, check chr and pos

# categorize indels

# We re-extracted the mutational signatures including, in addition to the 96 substitution types, two further classes of mutation: indels at short nucleotide repeats and indels with overlapping microhomology at breakpoint junctions. ... The immediate 5′ and 3′ sequence content of all indels was examined and the ones present at mono/polynucleotide repeats or microhomologies were included in the analyzed mutational catalogs as their respective types. 
# The sequences flanking each indel were interrogated for the presence of short tandem repeats or short stretches of identical sequence at the breakpoints (termed overlapping microhomology) (Figure 7B). Repeat-mediated indels were small (1–5 bp), present in all breast cancers, and comprised both deletions and insertions. Microhomology-mediated indels were larger (up to 50bp), mainly deletions and considerably more common in cases with BRCA1 or BRCA2 mutations (p = 2.2 × 10−16).

    # for repeats: pad interval by +/-5, then see if it overlaps a repeat region from ucsc Simple Repeats track

    # for microhomology, pull up/downstream bases and see if they're the same?
        # chr1 100 ACTT A
        # if nnnnACTT is upstream, and CTTnnnnn is downstream, it's MMEJ

    # or, just separate by size?
        # size = larger(len(ALT),len(REF))
        
        # then make two files - indels > 5 and indels < 5
        # use my count vars per person python script to get numbers